# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2Dgo8TA5qGGgvQt5Y58iS8QofXhtt8D
"""

code = """
from duckduckgo_search import DDGS
import requests, os
from PIL import Image
from io import BytesIO

def main():
    print("=== برنامج تحميل صور تلقائيًا من النصوص ===")
    text = input("اكتب النص هنا (الجمل مفصولة بنقطة .):\\n> ")

    # تقسيم النص لجمل
    sentences = [s.strip() for s in text.split('.') if s.strip()]

    if not sentences:
        print("❌ مفيش جمل اتكتبت!")
        return

    # مجلد للصور
    os.makedirs("images", exist_ok=True)

    # البحث وتحميل الصور
    for idx, sentence in enumerate(sentences, start=1):
        print(f"[{idx}] ببحث عن: {sentence}")
        try:
            results = DDGS().images(sentence, max_results=1)
            if results:
                url = results[0]['image']
                response = requests.get(url, timeout=10)
                img = Image.open(BytesIO(response.content))
                path = f"images/sentence_{idx}.jpg"
                img.save(path)
                print(f"✅ اتحفظت الصورة: {path}")
            else:
                print("⚠️ مفيش صور اتلاقت")
        except Exception as e:
            print("❌ حصل خطأ:", e)

    print("\\n🎉 خلصت! الصور موجودة في مجلد images")

if __name__ == "__main__":
    main()
"""

with open("main.py", "w", encoding="utf-8") as f:
    f.write(code)

print("✅ الملف main.py اتعمل، تقدر تنزله من File Browser في Colab")